#!/bin/sh

set -e
#set -x

# source debconf stuff
if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
fi

# source dbconfig-common stuff
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
	. /usr/share/dbconfig-common/dpkg/config.mysql 
	dbc_go kommunikator $@
fi

