#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/yate" ] && [ -L "/etc/init.d/yate" ] \
	   && [ $(readlink -f "/etc/init.d/yate") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/yate"
	fi
fi
# End automatically added section
