#!/bin/sh 

set -e

case "$1" in
    purge)
	deluser --quiet --system yate || true
	delgroup --quiet --system yate || true
	rm -rf /var/lib/yate
	if [ -h /etc/yate/modules-enabled ]; then
		rm /etc/yate/modules-enabled
	fi
	
	if [ -h /etc/yate/scripts ]; then
		rm /etc/yate/scripts
	fi
	
	if [ -h /etc/yate/sounds ]; then
		rm /etc/yate/sounds
	fi
	;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

    *)
	echo "postrm called with unknown argument \`$1'" >&2
        exit 0
esac

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section

